### ISSUE TITLE
Link to ANN post

### ISSUE THREAD

**Issue by tfiers** [Roger-luo/Ion#20]
I found this software through github, but had no idea what it does.
I googled "roger luo ion" and found this helpful thread: https://discourse.julialang.org/t/ann-the-ion-command-line-for-julia-developers-written-in-rust/94495

Maybe would be good to add a link to that in the readme? (temporarily, until the docs are up, I suppose)

**Comment by Roger-luo** [comment]
Ah thanks! I wasn't paying much attention to GitHub since I thought most people just use discourse.
