### ISSUE TITLE
Bug: grcov workflow/action - results report error(s)

### ISSUE THREAD

**Issue by diversable** [Roger-luo/Ion#22]
While attempting to fix the GRCov workflow file (which I've made progress on: see latest `update grcov` commits from the pull request adding the `ion template inspect --verbose` display logic. 

I'm currently blocked on this issue.. so, 
I've pasted the output from the failing test here:

"""
failures:

---- spec::registry::tests::test_registry stdout ----
thread 'spec::registry::tests::test_registry' panicked at 'called `Result::unwrap()` on an `Err` value: TOML parse error at line 1, column 1
  |
1 | 
  | ^
missing field `name`
', src/ion/spec/registry.rs:226:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- spec::registry::tests::test_registry_data stdout ----
thread 'spec::registry::tests::test_registry_data' panicked at 'called `Result::unwrap()` on an `Err` value: TOML parse error at line 1, column 1
  |
1 | 
  | ^
missing field `name`
', src/ion/spec/registry.rs:241:59

failures:
    spec::registry::tests::test_registry
    spec::registry::tests::test_registry_data

test result: FAILED. 15 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 18.66s

error: test failed, to rerun pass `-p ion --lib`
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101

"""

**Comment by Roger-luo** [comment]
This is because you don't have a valid Julia registry setup locally, you can run `ion up` to let Julia download the registry. I just added better error message in #23

**Comment by Roger-luo** [comment]
should be fixed now since we are not using that workflow anymore
